In [3]:
import pandas as pd

In [6]:
df = pd.read_csv(r'C:\Users\bvhvr\OneDrive\Documents\Masai\Masai-Module2\used_cars_messy.csv')

In [7]:
df.head()

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,2581,Renault Duster,Renault,Duster,7,67647,Dealer,Diesel,Manual,19.87,1461.0,83.80,5.0,575000.0
1,224,Maruti Wagon R,Maruti,Wagon R,3,52000,Dealer,CNG,Manual,33.54,998.0,67.04,5.0,435000.0
2,1803,Honda City,Honda,City,3,48959,Dealer,Petrol,Manual,NaN,1497.0,117.60,5.0,875000.0
3,2728,Mahindra Scorpio,Mahindra,Scorpio,6,82000,dealer,Diesel,Manual,15.4,2179.0,NaN,8.0,925000.0
4,14160,Mahindra XUV500,Mahindra,XUV500,4,34000,Dealer,Diesel,Automatic,16.0,2179.0,140.00,7.0,1175000.0

In [8]:
df['km_driven'].value_counts

<bound method IndexOpsMixin.value_counts of 0         67647
1         52000
2         48959
3         82000
4         34000
          ...
15656    127731
15657     59000
15658     20000
15659     15000
15660     30000
Name: km_driven, Length: 15661, dtype: str>

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15661 entries, 0 to 15660
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         15661 non-null  int64
 1   car_name           15661 non-null  str
 2   brand              15661 non-null  str
 3   model              15661 non-null  str
 4   vehicle_age        15661 non-null  int64
 5   km_driven          15661 non-null  str
 6   seller_type        15661 non-null  str
 7   fuel_type          15661 non-null  str
 8   transmission_type  15661 non-null  str
 9   mileage            14376 non-null  str
 10  engine             13792 non-null  float64
 11  max_power          14862 non-null  float64
 12  seats              15218 non-null  float64
 13  selling_price      15503 non-null  float64
dtypes: float64(4), int64(2), str(8)
memory usage: 1.7 MB

 # FUEL

In [10]:
# Before Cleaning
df['fuel_type'].unique()

<StringArray>
[  'Diesel',      'CNG',   'Petrol',  'Petrol ',   'DIESEL',  ' Petrol',
  'petrol ',   'PETROL',  ' Diesel',  'diesel ',      'LPG',   'petrol',
   'diesel', 'Electric']
Length: 14, dtype: str

In [11]:
df['fuel_type']=df['fuel_type'].astype(str).str.strip().str.title()

In [12]:
#After Cleaning 
df['fuel_type'].unique()

<StringArray>
['Diesel', 'Cng', 'Petrol', 'Lpg', 'Electric']
Length: 5, dtype: str



# seller_type

In [13]:
df['seller_type'].unique()

<StringArray>
[          'Dealer',           'dealer',       'Individual',
       'individual',           'DEALER', 'Trustmark Dealer',
        'Individul',      'Individuall',           'Delaer']
Length: 9, dtype: str

In [14]:
df['seller_type']=df['seller_type'].str.strip().str.title()

In [15]:
df['seller_type'].unique()

<StringArray>
[          'Dealer',       'Individual', 'Trustmark Dealer',
        'Individul',      'Individuall',           'Delaer']
Length: 6, dtype: str

In [16]:
map={'Delaer':'Dealer',
'Individul':'Individual',
'Individuall':'Individual',
}
df['seller_type']=df['seller_type'].replace(map)

In [17]:
df['seller_type'].unique()

<StringArray>
['Dealer', 'Individual', 'Trustmark Dealer']
Length: 3, dtype: str

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15661 entries, 0 to 15660
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         15661 non-null  int64
 1   car_name           15661 non-null  str
 2   brand              15661 non-null  str
 3   model              15661 non-null  str
 4   vehicle_age        15661 non-null  int64
 5   km_driven          15661 non-null  str
 6   seller_type        15661 non-null  str
 7   fuel_type          15661 non-null  str
 8   transmission_type  15661 non-null  str
 9   mileage            14376 non-null  str
 10  engine             13792 non-null  float64
 11  max_power          14862 non-null  float64
 12  seats              15218 non-null  float64
 13  selling_price      15503 non-null  float64
dtypes: float64(4), int64(2), str(8)
memory usage: 1.7 MB

In [19]:
df['transmission_type'].unique()

<StringArray>
['Manual', 'Automatic']
Length: 2, dtype: str

# Numerical Cols

In [20]:
df['vehicle_age'].unique()

array([ 7,  3,  6,  4, 12,  2, 10,  1,  5,  8, 11, 13,  9, 16, 14, 15, 17,
       18, 29, 25, 21,  0, 19, 22])

In [21]:
df['km_driven'].unique()

<StringArray>
[ '67647',  '52000',  '48959',  '82000',  '34000',  '73000',  '88000',
  '50000',  '30000',  '75220',
 ...
  '33350',  '66523', '425785',  '50898',  '17999',  '43001',  '43200',
  '39337',  '66850', '127731']
Length: 3868, dtype: str

In [22]:
df['km_driven'].value_counts()

km_driven
50000     554
40000     472
70000     462
60000     448
30000     360
         ...
43001       1
43200       1
39337       1
66850       1
127731      1
Name: count, Length: 3868, dtype: int64

In [23]:
invalid_km_Driven=df[pd.to_numeric(df['km_driven'],errors='coerce').isna()]

In [24]:
invalid_km_Driven.shape
invalid_km_Driven['km_driven'].unique()

<StringArray>
[     '7,369',  '42000 kms',   '32000 km',  '62000 kms',  '40000 kms',
  '43652 kms',     '22,128',   '50000 km',   '54000 km', '100000 kms',
 ...
  '16502 kms',      '8,403',   '98000 km',     '14,000',  '70000 kms',
  '144321 km',     '45,000',  '31497 kms',     '88,466',    '160,000']
Length: 179, dtype: str

In [25]:
df['km_driven']=df['km_driven'].astype(str).str.replace('[A-Za-z]',"",regex=True)

In [26]:
km_Driven=df[pd.to_numeric(df['km_driven'],errors='coerce').isna()]

In [27]:
invalid_km_Driven=df[pd.to_numeric(df['km_driven'],errors='coerce').isna()]

In [28]:
invalid_km_Driven.shape
invalid_km_Driven['km_driven'].unique()

<StringArray>
[  '7,369',  '22,128',  '39,757',  '63,000',  '82,250',  '27,599',  '30,000',
  '77,000',  '65,000',  '10,000',  '70,000',  '55,001',  '35,000',  '60,000',
 '110,000',  '12,000',  '37,000',  '80,000', '150,000',  '72,000',  '91,795',
   '5,381',  '71,000',  '20,000',  '68,387',  '47,347',  '48,000', '155,000',
  '25,000',  '62,500',  '56,000',   '5,000',   '6,000',  '28,001',  '58,000',
  '51,000',  '39,000',  '55,000',  '82,000',  '77,433',  '32,241', '100,000',
   '9,000',  '63,581',  '97,000',  '90,000',  '18,000', '120,000',  '16,631',
  '83,000',  '40,000',  '75,000',  '13,000', '130,600',  '15,000',   '8,403',
  '14,000',  '45,000',  '88,466', '160,000']
Length: 60, dtype: str

In [29]:
df['km_driven']=df['km_driven'].astype(str).str.replace('[A-Za-z,]',"",regex=True)

In [30]:
invalid_km_Driven=df[pd.to_numeric(df['km_driven'],errors='coerce').isna()]
invalid_km_Driven.shape
invalid_km_Driven['km_driven'].unique()

<StringArray>
[]
Length: 0, dtype: str

In [31]:
df['km_driven']=pd.to_numeric(df['km_driven'],errors='coerce')

In [32]:
invalid=df[df['mileage'].astype(str).str.contains('[A-Za-z,]',regex=True,na=False)]

In [33]:
invalid['mileage'].unique()

<StringArray>
['33.54 kmpl', '13.68 kmpl', '22.74 kmpl',  '17.4 kmpl', '21.56 kmpl',
  '24.3 kmpl', '17.01 kmpl',  '18.9 kmpl',  '16.0 kmpl',  '15.4 kmpl',
 ...
  '14.0 kmpl',  '11.5 kmpl', '18.69 kmpl', '23.01 kmpl', '25.32 kmpl',
 '19.59 kmpl', '18.12 kmpl', '28.09 kmpl',  '17.7 kmpl', '24.04 kmpl']
Length: 109, dtype: str

In [34]:
df['mileage']=df['mileage'].astype(str).str.replace('[A-Za-z,]',"",regex=True)

In [35]:
invalid=df[df['mileage'].astype(str).str.contains('[A-Za-z,]',regex=True,na=False)]

In [36]:
invalid['mileage'].unique()

<StringArray>
[]
Length: 0, dtype: str

In [37]:
df['mileage']=pd.to_numeric(df['mileage'],errors='coerce')

In [38]:
invalid_engine=df[df['engine'].astype(str).str.contains('[A-Za-z,]',regex=True,na=False)]

In [39]:
invalid_engine['engine'].unique()

array([], dtype=float64)

In [40]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15661 entries, 0 to 15660
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         15661 non-null  int64
 1   car_name           15661 non-null  str
 2   brand              15661 non-null  str
 3   model              15661 non-null  str
 4   vehicle_age        15661 non-null  int64
 5   km_driven          15661 non-null  int64
 6   seller_type        15661 non-null  str
 7   fuel_type          15661 non-null  str
 8   transmission_type  15661 non-null  str
 9   mileage            14376 non-null  float64
 10  engine             13792 non-null  float64
 11  max_power          14862 non-null  float64
 12  seats              15218 non-null  float64
 13  selling_price      15503 non-null  float64
dtypes: float64(5), int64(3), str(6)
memory usage: 1.7 MB

In [41]:
df.describe()

,Unnamed: 0,vehicle_age,km_driven,mileage,engine,max_power,seats,selling_price
count,15661.000000,15661.000000,1.566100e+04,14376.000000,13792.000000,14862.000000,15218.000000,1.550300e+04
mean,9808.189643,6.036843,5.562075e+04,19.703828,1480.489342,100.513582,5.324418,1.032764e+06
std,5642.981540,3.015072,5.152178e+04,4.179440,511.446057,42.854632,0.805993,1.607380e+07
min,0.000000,0.000000,1.000000e+02,4.000000,793.000000,38.400000,0.000000,5.000000e+02
25%,4901.000000,4.000000,3.000000e+04,17.000000,1197.000000,74.000000,5.000000,3.850000e+05
50%,9858.000000,6.000000,5.000000e+04,19.670000,1248.000000,88.500000,5.000000,5.550000e+05
75%,14666.000000,8.000000,7.000000e+04,22.700000,1582.000000,117.300000,5.000000,8.250000e+05
max,19543.000000,29.000000,3.800000e+06,33.540000,6592.000000,626.000000,9.000000,1.000000e+09

In [46]:
import numpy as np 
import matplotlib.pyplot as plt 
from sklearn.model_selection import train_test_split,KFold,cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error,r2_score,mean_squared_error

In [47]:
df=pd.read_csv(r'C:\Users\bvhvr\OneDrive\Documents\Masai\Masai-Module2\IM Session 30 - Regression Regularization\cardekho_dataset (1).csv')

In [49]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15411 entries, 0 to 15410
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         15411 non-null  int64
 1   car_name           15411 non-null  str
 2   brand              15411 non-null  str
 3   model              15411 non-null  str
 4   vehicle_age        15411 non-null  int64
 5   km_driven          15411 non-null  int64
 6   seller_type        15411 non-null  str
 7   fuel_type          15411 non-null  str
 8   transmission_type  15411 non-null  str
 9   mileage            15411 non-null  float64
 10  engine             15411 non-null  int64
 11  max_power          15411 non-null  float64
 12  seats              15411 non-null  int64
 13  selling_price      15411 non-null  int64
dtypes: float64(2), int64(6), str(6)
memory usage: 1.6 MB

In [50]:
df.columns.tolist()

['Unnamed: 0',
 'car_name',
 'brand',
 'model',
 'vehicle_age',
 'km_driven',
 'seller_type',
 'fuel_type',
 'transmission_type',
 'mileage',
 'engine',
 'max_power',
 'seats',
 'selling_price']

In [51]:
df.shape

(15411, 14)

In [52]:
df.head()

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [55]:
df=pd.get_dummies(df,columns=['brand','seller_type','fuel_type','transmission_type'],drop_first=True)

In [56]:
df.shape

(15411, 48)

In [58]:
df.head()

,Unnamed: 0,car_name,model,vehicle_age,km_driven,mileage,engine,max_power,seats,selling_price,...,brand_Toyota,brand_Volkswagen,brand_Volvo,seller_type_Individual,seller_type_Trustmark Dealer,fuel_type_Diesel,fuel_type_Electric,fuel_type_LPG,fuel_type_Petrol,transmission_type_Manual
0,0,Maruti Alto,Alto,9,120000,19.70,796,46.30,5,120000,...,False,False,False,True,False,False,False,False,True,True
1,1,Hyundai Grand,Grand,5,20000,18.90,1197,82.00,5,550000,...,False,False,False,True,False,False,False,False,True,True
2,2,Hyundai i20,i20,11,60000,17.00,1197,80.00,5,215000,...,False,False,False,True,False,False,False,False,True,True
3,3,Maruti Alto,Alto,9,37000,20.92,998,67.10,5,226000,...,False,False,False,True,False,False,False,False,True,True
4,4,Ford Ecosport,Ecosport,6,30000,22.77,1498,98.59,5,570000,...,False,False,False,False,False,True,False,False,False,True

In [ ]:
df.drop